## Automatically generated by odin 1.5.9 - do not edit
tbmod0_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "tbmod0_rhs_dde",
      rhs_desolve = "tbmod0_rhs_desolve",
      initmod_desolve = "tbmod0_initmod_desolve"),
    dll = "ecrins",
    user = c("inflow", "long_release", "long_short", "open_release",
             "parm_frac_ATT", "parm_frac_CD", "parm_frac_E",
             "parm_frac_epTB", "parm_frac_L", "parm_frac_lpTB",
             "parm_frac_SD", "parm_frac_U", "parm_ifrac_ATT",
             "parm_ifrac_CD", "parm_ifrac_E", "parm_ifrac_epTB",
             "parm_ifrac_L", "parm_ifrac_lpTB", "parm_ifrac_prevTPT",
             "parm_ifrac_SD", "parm_ifrac_U", "parm_init_PPD",
             "previous_remand", "remand_long", "remand_release",
             "remand_short", "short_open", "short_release", "att_time",
             "disc_rate", "inflow_toATT_P", "inflow_toATT_rest",
             "inflow_toATT_TB", "inflow_toTPT_L", "late_post_time", "mort"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("tbmod0_rhs_dde", package = "ecrins")
        .C("tbmod0_rhs_desolve", package = "ecrins")
        .C("tbmod0_initmod_desolve", package = "ecrins")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("tbmod0_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "ecrins")
    },

    update_metadata = function() {
      meta <- .Call("tbmod0_metadata", private$ptr,
                    PACKAGE = "ecrins")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("tbmod0_create", user, PACKAGE = "ecrins")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/tbmod0.json", mustWork = TRUE,
                             package = "ecrins")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("tbmod0_set_user", private$ptr, user, PACKAGE = "ecrins")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("tbmod0_initial_conditions", private$ptr, t, PACKAGE = "ecrins")
    },

    rhs = function(t, y) {
      .Call("tbmod0_rhs_r", private$ptr, t, y, PACKAGE = "ecrins")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("tbmod0_contents", private$ptr, PACKAGE = "ecrins")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


tbmod0 <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("tbmod0")
  tbmod0_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(tbmod0) <- "odin_generator"
attr(tbmod0, "generator") <- tbmod0_
